device: cuda:2
Current cuda device  0
ViTBase Network
full_model_tuning_only
Classes ++++ ['00_dog', '01_bird', '02_wheeled vehicle', '03_reptile', '04_carnivore', '05_insect', '06_musical instrument', '07_primate', '08_fish']
Loading dataset
0it [00:00, ?it/s]1it [00:00,  4.38it/s]2it [00:00,  4.21it/s]3it [00:00,  3.67it/s]4it [00:01,  3.01it/s]5it [00:01,  2.81it/s]6it [00:01,  2.85it/s]6it [00:01,  3.08it/s]
env_mixed_next_acc 0.6494623655913978
env_mixed_rand_acc 0.6893667861409797
env_mixed_same_acc 0.8007168458781362
env_no_fg_acc 0.5634408602150538
env_only_fg_acc 0.7020310633213859
env_original_acc 0.9526881720430107
device: cuda:2
Current cuda device  0
ViTBase Network
full_model_tuning_only
Classes ++++ ['00_dog', '01_bird', '02_wheeled vehicle', '03_reptile', '04_carnivore', '05_insect', '06_musical instrument', '07_primate', '08_fish']
Loading dataset
0it [00:00, ?it/s]1it [00:00,  2.35it/s]2it [00:00,  2.97it/s]3it [00:01,  2.57it/s]4it [00:01,  2.42it/s]5it [00:02,  2.26it/s]6it [00:02,  2.30it/s]6it [00:02,  2.38it/s]
Traceback (most recent call last):
  File "evaluvation.py", line 233, in <module>
    acc = validation_accuracy(model, loader, weights, device, args.dataset, conversion_array)
  File "evaluvation.py", line 104, in validation_accuracy
    correct += (pred==y).sum().item()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cpu!
device: cuda:2
Current cuda device  0
ViTBase Network
full_model_tuning_only
Classes ++++ ['00_dog', '01_bird', '02_wheeled vehicle', '03_reptile', '04_carnivore', '05_insect', '06_musical instrument', '07_primate', '08_fish']
Loading dataset
0it [00:00, ?it/s]1it [00:00,  2.51it/s]2it [00:00,  3.24it/s]3it [00:01,  2.91it/s]4it [00:01,  2.58it/s]5it [00:01,  2.46it/s]6it [00:02,  2.25it/s]6it [00:02,  2.45it/s]
Traceback (most recent call last):
  File "evaluvation.py", line 234, in <module>
    acc = validation_accuracy(model, loader, weights, device, args.dataset, conversion_array)
  File "evaluvation.py", line 90, in validation_accuracy
    model = nn.DataParallel(model,device_ids=[0])
NameError: name 'nn' is not defined
device: cuda:2
Current cuda device  0
ViTBase Network
full_model_tuning_only
Classes ++++ ['00_dog', '01_bird', '02_wheeled vehicle', '03_reptile', '04_carnivore', '05_insect', '06_musical instrument', '07_primate', '08_fish']
Loading dataset
0it [00:00, ?it/s]1it [00:00,  3.89it/s]2it [00:00,  3.39it/s]3it [00:01,  2.71it/s]4it [00:01,  2.59it/s]5it [00:01,  2.52it/s]6it [00:02,  2.61it/s]6it [00:02,  2.70it/s]
Traceback (most recent call last):
  File "evaluvation.py", line 235, in <module>
    acc = validation_accuracy(model, loader, weights, device, args.dataset, conversion_array)
  File "evaluvation.py", line 96, in validation_accuracy
    p = model.predict(x)
  File "/home/kavindya/anaconda3/envs/ViT_DGbed_2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DataParallel' object has no attribute 'predict'
